name: Plugin action
on:
  push:
    branches: ['main', 'master']
  pull_request:
    types: [opened, edited, reopened]
  release:
    types: [published]

jobs:
  plugin-action:
    uses: matmair/inventree-meta-plugin/.github/workflows/plugin_action.yaml@next
    permissions:
      id-token: write
    with:
      pypi_trusted_publishers: true

